name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          use-only-tar-bz2: true
          channels: simonflueckiger, defaults
      - name: Install tesserocr
        run: conda install -c simonflueckiger tesserocr
      - uses: actions/checkout@v4
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          options: --onefile
          path: .

      - uses: actions/upload-artifact@v4
        with:
          name: tetris_sound.exe
          path: dist/windows
